name: cleanup

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: dev-${{ steps.branch-name.outputs.current_branch }}
          onlyDeactivateDeployments: true
