name: git-windows

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Print config
        shell: bash
        run: |
          echo "Listing home directory..."
          ls -la ~
          echo "Showing global git config..."
          git config --global --list
          
      - uses: actions/checkout@v4
      
      - name: Print config (after checkout)
        shell: bash
        run: |
          echo "Listing home directory..."
          ls -la ~
          echo "Showing global git config..."
          git config --global --list
          echo "Showing git config..."
          git config --list
